FORMAT: 1A

# Introduction
Esta api tem como responsabilidade armazenar vendas e recomendar items com base em pesquisa nos dados de vendas armazenados.

## Architecture
Os seguintes itens descrevem as tecnologias utilizadas

+ MongoDB 4.*
+ PHP 7.*
+ Nginx

