<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class NuvemDocumentsOrderHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate(object $document, array $data, array $hints = array()): array
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoDB\BSON\ObjectId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['number']) || (! empty($this->class->fieldMappings['number']['nullable']) && array_key_exists('number', $data))) {
            $value = $data['number'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['number']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['number']->setValue($document, $return);
            $hydratedData['number'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['totalValue']) || (! empty($this->class->fieldMappings['totalValue']['nullable']) && array_key_exists('totalValue', $data))) {
            $value = $data['totalValue'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['totalValue']['type'];
                $return = (float) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['totalValue']->setValue($document, $return);
            $hydratedData['totalValue'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['createdAt'])) {
            $value = $data['createdAt'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['createdAt']->setValue($document, clone $return);
            $hydratedData['createdAt'] = $return;
        }

        /** @Many */
        $mongoData = isset($data['items']) ? $data['items'] : null;
        $return = $this->dm->getConfiguration()->getPersistentCollectionFactory()->create($this->dm, $this->class->fieldMappings['items']);
        $return->setHints($hints);
        $return->setOwner($document, $this->class->fieldMappings['items']);
        $return->setInitialized(false);
        if ($mongoData) {
            $return->setMongoData($mongoData);
        }
        $this->class->reflFields['items']->setValue($document, $return);
        $hydratedData['items'] = $return;
        return $hydratedData;
    }
}